### ISSUE TITLE
Error: `no suitable image found.  Did find` 

### ISSUE THREAD

**Issue by albatrosary** [ashiras/ashiras.dev#1]
Error `gulp serve`

``` bash
$ gulp serve
[10:44:58] Using gulpfile ~/Sandbox/ashiras.dev/gulpfile.js
[10:44:58] Starting 'styles'...
[10:44:58] 'styles' errored after 62 ms
[10:44:58] Error: dlopen(/Users/albatrosary/Sandbox/ashiras.dev/node_modules/node-sass/vendor/darwin-x64-47/binding.node, 1): no suitable image found.  Did find:
    /Users/albatrosary/Sandbox/ashiras.dev/node_modules/node-sass/vendor/darwin-x64-47/binding.node: truncated mach-o error: segment __LINKEDIT extends to 2602136 which is past end of file 1913392
    at Error (native)
    at Object.Module._extensions..node (module.js:440:18)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/albatrosary/Sandbox/ashiras.dev/node_modules/node-sass/lib/index.js:24:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by albatrosary** [comment]
see: https://github.com/dlmanning/gulp-sass/issues/454

`npm rebuild node-sass`
