### ISSUE TITLE
Error: Unhandled rejection Error

### ISSUE THREAD

**Issue by albatrosary** [ashiras/ashiras.dev#2]
``` bash
$ gulp build
[11:17:02] Using gulpfile ~/Sandbox/ashiras.dev/gulpfile.js
[11:17:02] Starting 'lint'...
[11:17:02] Starting 'styles'...
[11:17:03] Starting 'scripts'...
[11:17:03] Starting 'images'...
[11:17:04] Starting 'fonts'...
[11:17:04] Starting 'extras'...
[11:17:04] Finished 'lint' after 1.71 s
Unhandled rejection Error: spawn /Users/albatrosary/Sandbox/ashiras.dev/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at exports._errnoException (util.js:893:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

[11:17:04] Finished 'scripts' after 1.13 s
[11:17:04] Finished 'styles' after 1.44 s
[11:17:04] Starting 'html'...
[11:17:04] Finished 'extras' after 815 ms
[11:17:04] Finished 'html' after 443 ms
[11:17:04] Finished 'fonts' after 849 ms
```

**Comment by albatrosary** [comment]
#75ff8c8
